// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzUNR5LGOmLvZYVUS5EfHoT9YdK6xt32Y',
    appId: '1:769888184610:web:a87faa937783f4ca8e9d7b',
    messagingSenderId: '769888184610',
    projectId: 'booky-4eb2c',
    authDomain: 'booky-4eb2c.firebaseapp.com',
    storageBucket: 'booky-4eb2c.firebasestorage.app',
    measurementId: 'G-6DT4PF8HL3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUvA8jaI1bDE34_9WV8hcY9rMSL445x2w',
    appId: '1:769888184610:android:cb04b39793bcfc6c8e9d7b',
    messagingSenderId: '769888184610',
    projectId: 'booky-4eb2c',
    storageBucket: 'booky-4eb2c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARrzGTh2_tg5T4SPcQZT3BUTt-UZEhrwI',
    appId: '1:769888184610:ios:07a1beceac2a2fa98e9d7b',
    messagingSenderId: '769888184610',
    projectId: 'booky-4eb2c',
    storageBucket: 'booky-4eb2c.firebasestorage.app',
    iosClientId: '769888184610-o0oboh9jlduqkr125d5k04pif162ur1a.apps.googleusercontent.com',
    iosBundleId: 'com.example.writer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARrzGTh2_tg5T4SPcQZT3BUTt-UZEhrwI',
    appId: '1:769888184610:ios:07a1beceac2a2fa98e9d7b',
    messagingSenderId: '769888184610',
    projectId: 'booky-4eb2c',
    storageBucket: 'booky-4eb2c.firebasestorage.app',
    iosClientId: '769888184610-o0oboh9jlduqkr125d5k04pif162ur1a.apps.googleusercontent.com',
    iosBundleId: 'com.example.writer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzUNR5LGOmLvZYVUS5EfHoT9YdK6xt32Y',
    appId: '1:769888184610:web:a826378c7e457c7f8e9d7b',
    messagingSenderId: '769888184610',
    projectId: 'booky-4eb2c',
    authDomain: 'booky-4eb2c.firebaseapp.com',
    storageBucket: 'booky-4eb2c.firebasestorage.app',
    measurementId: 'G-28C34QPY9P',
  );
}
